const cards = [
  [
    {
      word: 'Action (set A)',
      image: './img/assets/img/draw.jpg',
    },
    {
      word: 'Action (set B)',
      image: './img/assets/img/run.jpg',
    },
    {
      word: 'Animal (set A)',
      image: './img/assets/img/cat.jpg',
    },
    {
      word: 'Animal (set B)',
      image: './img/assets/img/bird.jpg',
    },
    {
      word: 'Clothes',
      image: './img/assets/img/skirt.jpg',
    },
    {
      word: 'Emotions',
      image: './img/assets/img/happy.jpg',
    },
    {
      word: 'Fruit',
      image: './img/assets/img/apple.jpg',
    },
    {
      word: 'Transport',
      image: './img/assets/img/train.jpg',
    },
  ],
  [
    {
      word: 'cry',
      translation: 'плакать',
      image: './img/assets/img/cry.jpg',
      audioSrc: 'audio/cry.mp3',
      category: 'Action (Set A)',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: './img/assets/img/dance.jpg',
      audioSrc: 'audio/dance.mp3',
      category: 'Action (Set A)',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: './img/assets/img/dive.jpg',
      audioSrc: 'audio/dive.mp3',
      category: 'Action (Set A)',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: './img/assets/img/draw.jpg',
      audioSrc: 'audio/draw.mp3',
      category: 'Action (Set A)',
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: './img/assets/img/fish.jpg',
      audioSrc: 'audio/fish.mp3',
      category: 'Action (Set A)',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: './img/assets/img/fly.jpg',
      audioSrc: 'audio/fly.mp3',
      category: 'Action (Set A)',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: './img/assets/img/hug.jpg',
      audioSrc: 'audio/hug.mp3',
      category: 'Action (Set A)',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: './img/assets/img/jump.jpg',
      audioSrc: 'audio/jump.mp3',
      category: 'Action (Set A)',
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      image: './img/assets/img/open.jpg',
      audioSrc: 'audio/open.mp3',
      category: 'Action (Set B)',
    },
    {
      word: 'play',
      translation: 'играть',
      image: './img/assets/img/play.jpg',
      audioSrc: 'audio/play.mp3',
      category: 'Action (Set B)',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: './img/assets/img/point.jpg',
      audioSrc: 'audio/point.mp3',
      category: 'Action (Set B)',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: './img/assets/img/ride.jpg',
      audioSrc: 'audio/ride.mp3',
      category: 'Action (Set B)',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: './img/assets/img/run.jpg',
      audioSrc: 'audio/run.mp3',
      category: 'Action (Set B)',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: './img/assets/img/sing.jpg',
      audioSrc: 'audio/sing.mp3',
      category: 'Action (Set B)',
    },
    {
      word: 'skip',
      translation: 'прыгать',
      image: './img/assets/img/skip.jpg',
      audioSrc: 'audio/skip.mp3',
      category: 'Action (Set B)',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: './img/assets/img/swim.jpg',
      audioSrc: 'audio/swim.mp3',
      category: 'Action (Set B)',
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: './img/assets/img/cat.jpg',
      audioSrc: 'audio/cat.mp3',
      category: 'Animal (Set A)',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: './img/assets/img/chick.jpg',
      audioSrc: 'audio/chick.mp3',
      category: 'Animal (Set A)',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: './img/assets/img/chicken.jpg',
      audioSrc: 'audio/chicken.mp3',
      category: 'Animal (Set A)',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: './img/assets/img/dog.jpg',
      audioSrc: 'audio/dog.mp3',
      category: 'Animal (Set A)',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: './img/assets/img/horse.jpg',
      audioSrc: 'audio/horse.mp3',
      category: 'Animal (Set A)',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: './img/assets/img/pig.jpg',
      audioSrc: 'audio/pig.mp3',
      category: 'Animal (Set A)',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: './img/assets/img/rabbit.jpg',
      audioSrc: 'audio/rabbit.mp3',
      category: 'Animal (Set A)',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: './img/assets/img/sheep.jpg',
      audioSrc: 'audio/sheep.mp3',
      category: 'Animal (Set A)',
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      image: './img/assets/img/bird.jpg',
      audioSrc: 'audio/bird.mp3',
      category: 'Animal (Set B)',
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: './img/assets/img/fish1.jpg',
      audioSrc: 'audio/fish.mp3',
      category: 'Animal (Set B)',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: './img/assets/img/frog.jpg',
      audioSrc: 'audio/frog.mp3',
      category: 'Animal (Set B)',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: './img/assets/img/giraffe.jpg',
      audioSrc: 'audio/giraffe.mp3',
      category: 'Animal (Set B)',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: './img/assets/img/lion.jpg',
      audioSrc: 'audio/lion.mp3',
      category: 'Animal (Set B)',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: './img/assets/img/mouse.jpg',
      audioSrc: 'audio/mouse.mp3',
      category: 'Animal (Set B)',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: './img/assets/img/turtle.jpg',
      audioSrc: 'audio/turtle.mp3',
      category: 'Animal (Set B)',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: './img/assets/img/dolphin.jpg',
      audioSrc: 'audio/dolphin.mp3',
      category: 'Animal (Set B)',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: './img/assets/img/skirt.jpg',
      audioSrc: 'audio/skirt.mp3',
      category: 'Clothes',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: './img/assets/img/pants.jpg',
      audioSrc: 'audio/pants.mp3',
      category: 'Clothes',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: './img/assets/img/blouse.jpg',
      audioSrc: 'audio/blouse.mp3',
      category: 'Clothes',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: './img/assets/img/dress.jpg',
      audioSrc: 'audio/dress.mp3',
      category: 'Clothes',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: './img/assets/img/boot.jpg',
      audioSrc: 'audio/boot.mp3',
      category: 'Clothes',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: './img/assets/img/shirt.jpg',
      audioSrc: 'audio/shirt.mp3',
      category: 'Clothes',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: './img/assets/img/coat.jpg',
      audioSrc: 'audio/coat.mp3',
      category: 'Clothes',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: './img/assets/img/shoe.jpg',
      audioSrc: 'audio/shoe.mp3',
      category: 'Clothes',
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: './img/assets/img/sad.jpg',
      audioSrc: 'audio/sad.mp3',
      category: 'Emotions',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: './img/assets/img/angry.jpg',
      audioSrc: 'audio/angry.mp3',
      category: 'Emotions',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: './img/assets/img/happy.jpg',
      audioSrc: 'audio/happy.mp3',
      category: 'Emotions',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: './img/assets/img/tired.jpg',
      audioSrc: 'audio/tired.mp3',
      category: 'Emotions',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: './img/assets/img/surprised.jpg',
      audioSrc: 'audio/surprised.mp3',
      category: 'Emotions',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: './img/assets/img/scared.jpg',
      audioSrc: 'audio/scared.mp3',
      category: 'Emotions',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: './img/assets/img/smile.jpg',
      audioSrc: 'audio/smile.mp3',
      category: 'Emotions',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: './img/assets/img/laugh.jpg',
      audioSrc: 'audio/laugh.mp3',
      category: 'Emotions',
    },
  ],
  [
    {
      word: 'apple',
      translation: 'яблоко',
      image: './img/assets/img/apple.jpg',
      audioSrc: 'audio/apple.mp3',
      category: 'Fruit',
    },
    {
      word: 'banana',
      translation: 'банан',
      image: './img/assets/img/banana.jpg',
      audioSrc: 'audio/banana.mp3',
      category: 'Fruit',
    },
    {
      word: 'blueberries',
      translation: 'черника',
      image: './img/assets/img/blueberries.jpg',
      audioSrc: 'audio/blueberries.mp3',
      category: 'Fruit',
    },
    {
      word: 'cherries',
      translation: 'вишня',
      image: './img/assets/img/cherries.jpg',
      audioSrc: 'audio/cherries.mp3',
      category: 'Fruit',
    },
    {
      word: 'coconut',
      translation: 'кокос',
      image: './img/assets/img/coconut.jpg',
      audioSrc: 'audio/coconut.mp3',
      category: 'Fruit',
    },
    {
      word: 'kiwi',
      translation: 'киви',
      image: './img/assets/img/kiwi.jpg',
      audioSrc: 'audio/kiwi.mp3',
      category: 'Fruit',
    },
    {
      word: 'lemon',
      translation: 'лемон',
      image: './img/assets/img/lemon.jpg',
      audioSrc: 'audio/lemon.mp3',
      category: 'Fruit',
    },
    {
      word: 'orange',
      translation: 'апельсин',
      image: './img/assets/img/orange.jpg',
      audioSrc: 'audio/orange.mp3',
      category: 'Fruit',
    },
  ],
  [
    {
      word: 'airplane',
      translation: 'самолет',
      image: './img/assets/img/airplane.jpg',
      audioSrc: 'audio/airplane.mp3',
      category: 'Transport',
    },
    {
      word: 'bus',
      translation: 'автобус',
      image: './img/assets/img/bus.jpg',
      audioSrc: 'audio/bus.mp3',
      category: 'Transport',
    },
    {
      word: 'car',
      translation: 'автомобиль',
      image: './img/assets/img/car.jpg',
      audioSrc: 'audio/car.mp3',
      category: 'Transport',
    },
    {
      word: 'ship',
      translation: 'корабль',
      image: './img/assets/img/ship.jpg',
      audioSrc: 'audio/ship.mp3',
      category: 'Transport',
    },
    {
      word: 'tractor',
      translation: 'трактор',
      image: './img/assets/img/tractor.jpg',
      audioSrc: 'audio/tractor.mp3',
      category: 'Transport',
    },
    {
      word: 'train',
      translation: 'поезд',
      image: './img/assets/img/train.jpg',
      audioSrc: 'audio/train.mp3',
      category: 'Transport',
    },
    {
      word: 'bicycle',
      translation: 'велосипед',
      image: './img/assets/img/bicycle.jpg',
      audioSrc: 'audio/bicycle.mp3',
      category: 'Transport',
    },
    {
      word: 'helicopter',
      translation: 'вертолет',
      image: './img/assets/img/helicopter.jpg',
      audioSrc: 'audio/helicopter.mp3',
      category: 'Transport',
    },
  ],
];


export default cards;
